name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Message
        run: echo "CI/CD Pipeline Started"

      - name: List Files
        run: ls -la

      - name: Success
        run: echo "CI/CD Pipeline Executed Successfully!"